### PR TITLE
Bird Sighting Analysis Arjun, 3rd May 2024 by EOD, Sprint 2 pull request

### PR DESCRIPTION
**Pull request by 13dothraki**
This is my updated ipynb file where i have predicted the sightings and cleared the code to look more butified

### CODE REVIEW

**Review by molliefernandez — CHANGES_REQUESTED** [review]
Hi @13dothraki 
Over all the use case is well laid out, just a few things to note:
- There are a couple of grammar and spelling mistakes eg. "Explanation"
- I love that you have explained what you are doing throughout the use case, it really represents what we are trying to do with creating use case tutorials, great work
- Some of your maps aren't displaying at the top of the use case
- Also change the name at the top of your use case from ChildCare Facilities to Bird Sightings analysis. 

Otherwise the use case is coming along nicely, with a bit of a spell check and

**Comment by 13dothraki** [comment]
Sorry I don't understand what you mean by some of maps are not displaying, my whole code is running perfectly according to me

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 13dothraki** [comment]
Made all the changes, use case and ready to publish and done pull request too

**Review by AliColli — CHANGES_REQUESTED** [review]
Maps etc opening fine in https://nbviewer.org/.
Use case may need a little updating next trimester (just a summary and orientation of the axis labels for the last plot as they're hard to read.) 
Can you please move your use case (all 3 files) into "UPDATE NEEDED" file and update your Trello card and move it to the backlog?

**Comment by leakydishes** [comment]
Hi @13dothraki 

This branch had an error being deployed
1 failed deployment

Please do the following ASAP
You need to re-fetch with main and then resubmit your request. 
This pull request is over 2 weeks old. We are now in the end of Sprint 3 - last pull request. Please follow information on announcement for steps required.

[Sprint 3 GitHub/ Trello Reminders](https://teams.microsoft.com/l/message/19:7b8edaaa927d404db49a935081398d92@thread.tacv2/1715091138485?tenantId=d02378ec-1688-46d5-8540-1c28b5f470f6&groupId=a3977aab-e4c1-4a33-8fd8-b0e7f10b979c&parentMessageId=1715091138485&teamName=Chameleon&channelName=City%20Of%20Melbourne&createdTime=1715091138485)

**Pull request closed without merging**
