### PR TITLE
DATA SCIENCE - MELBOURNE HOUSE PRICE EVALUATION - COMPLETED 

### PR DESCRIPTION
**Pull request by s220313209**
This is the final version of the project MELBOURNE HOUSE PRICE EVALUATION, including:
1. The coding file - preprocessing, applying machine learning, data visualisation, modelling.
2. The python file app.py and attachments for a local application which users can interact with.

### CODE REVIEW

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi @s220313209, the use case looks amazing. However, a few modifications are required:
1. pairplot and heatmap needs a title
2. keep only the final ipynb and remove the rest ipynb files since I noticed the final one has all the code
3. You are using 2 csv files, but the folder only has 1 so please add the 2nd csv file inside the folder too.
4. It would be great if you could add both the csv files in the "DEPENDENCIES" folder -> go to https://github.com/Chameleon-company/MOP-Code/tree/master/datascience/usecases/DEPENDENCIES -> create a folder by the name of your usecase -> put the csv files there (this ensures they are backed up since they are outside CoM website)
5. The .json file and .html files are missing -> create them as explained in the channel post/week-10 DS video
6. Move the folder from Playground to "READY TO PUBLISH" folder (Your Playground should not have anything from your usecase)

**Review by kitkatch — COMMENTED** [review]
Hi Bao, 

Awesome work. Just the minor changes as Samiha mentioned. Otherwise all is good. :)

**Comment by Samiha-Haque** [comment]
hi @s220313209, do mention us in comments if you are done fixing the code. It's merely 1 hr to go till submission!

**Comment by s220313209** [comment]
Hi @Samiha-Haque 
Can you see my new commits?
I created a new folder in READY TO PUBLIC and uploaded all the files, please check and tell me if it need any changes.
Thank you

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Sorry @s220313209 but you changed the name of the T2 2024 folder, please keep files inside the T2 2024 folder and do not change its name. The use case files should be in a folder with your use case name inside T2 2024. Also remove all your folders from playground.

**Pull request closed without merging**
