### PR TITLE
Tharusha cao&akintomiwa james : Function List 

### PR DESCRIPTION
**Pull request by TharushaCao**
This is a function list where I and akintomiwa james are working on , it is at its early stages and adding as many functions as possible .

to do:

- Will be working on the appendix 
- more visually appealing 
- probably test with a GUI or HTML way 
- add more functions

### CODE REVIEW

**Review by leakydishes — CHANGES_REQUESTED** [review]
Good Introduction, consider table of contents to include all functions/ purpose - is this your appendix that is in progress?
#### *Function 1*: *Explain why/ what it does*

#### Need to fix:
- Missing markdowns in some cells
- Missing 'A' in ---- ppendix)
- Folium map is not showing
- Empty cells (under correlation heatmap) need to delete
- Add next steps (in progress) in markdown or in comments in code block
This is if you commit code and then can't attend/ finish someone else can finish etc.

#### For next pull request:
- Markdown explain 'why' you are passing datasets ect to return new df. 
You have done this roughly in (Get column names in a list ( Easy to copy over ))

@TharushaCao

**Comment by TharushaCao** [comment]
> Good Introduction, consider table of contents to include all functions/ purpose - is this your appendix that is in progress?
> 
> #### _Function 1_: _Explain why/ what it does_
> #### Need to fix:
> * Missing markdowns in some cells
> * Missing 'A' in ---- ppendix)
> * Folium map is not showing
> * Empty cells (under correlation heatmap) need to delete
> * Add next steps (in progress) in markdown or in comments in code block
>   This is if you commit code and then can't attend/ finish someone else can finish etc.
> 
> #### For next pull request:
> * Markdown explain 'why' you are passing datasets ect to return new df.
>   You have done this roughly in (Get column names in a list ( Easy to copy over ))
> 
> @TharushaCao

@leakydishes  , Yes appendix is still in progress, I'm keeping the appendix as mainly a placeholder ( did update for now )
- The folium maps are a work in progress I'm going in a more methodical order starting with pre-processing
- Empty cells are removed, some are placeholder for testing 
- added a next steps, still in progress ( depends on how many I get done first )

Note: This is still in the early stages, takes a lot of work to get things working. I need to figure out how to extract coordinates (function) because not all datasets contain the same column name for it hence the folium maps not working yet.

**Comment by TharushaCao** [comment]
Git conflict resolved

**Review by twar9432 — APPROVED** [review]

**Review by TharushaCao — COMMENTED** [review]
changes are made

**Review by leakydishes — CHANGES_REQUESTED** [review]
Hi @TharushaCao and James (James I cant find your github username),

Thank you for your patience, i can see you have been working on this pull request since April. But as we have finished Sprint 3 and moving into READY_ONLY with final pull requests, PLAYGROUND directory is required to be deleted ready for next trimester. 

Please do the following ASAP
1. Move your files to a new directory in 'READY TO BE PUBLISHED' OR 'UPDATED NEEDED'
2. Delete your old directory in PLAYGROUND. 
3. Re-request Pull request 
4. After you have been re-approved you can then merge pull request. 

Thank you!

**Comment by TharushaCao** [comment]
> Hi @TharushaCao and James (James I cant find your github username),
> 
> Thank you for your patience, i can see you have been working on this pull request since April. But as we have finished Sprint 3 and moving into READY_ONLY with final pull requests, PLAYGROUND directory is required to be deleted ready for next trimester.
> 
> Please do the following ASAP
> 
> 1. Move your files to a new directory in 'READY TO BE PUBLISHED' OR 'UPDATED NEEDED'
> 2. Delete your old directory in PLAYGROUND.
> 3. Re-request Pull request
> 4. After you have been re-approved you can then merge pull request.
> 
> Thank you!

hi @leakydishes  @remmzytom is James , Will move to READ_ONLY . I already gave James a handover of the function list for him to contribute in the next trimester :)

**Comment by TharushaCao** [comment]
MOved to update needed @leakydishes

**Review by leakydishes — APPROVED** [review]
Perfect looks great! 

You can merge now @TharushaCao

**Pull request merged**
