### PR TITLE
Data Science Team - Soil Analysis and Prediction: 60% complete

### PR DESCRIPTION
**Pull request by trostov**
- Imported the datasets 
- Cleaned and organised the data
- Separated and merged the data into two dataframes
- Created an initial visualization
- Created multiple visualizations comparing different factors

### CODE REVIEW

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi Thomas,
1. Are both the datasets from different sources, because I only see Weather data in your folder, if not please use API2.1v for loading the soil dataset.
2.  If possible add legends to code blocks 44 and 46.
Other than that, code looks great!

**Comment by trostov** [comment]
Thanks Samiha, I uncommented the API downloading for the soil dataset.
As for legends, the graphs at 44/46 are just meant to show a distribution, the legend would be way too much clutter there

**Review by Samiha-Haque — APPROVED** [review]
Thanks Thomas! 
Maybe you can add an empty string in the api part of soil data and some descriptions for the graphs indicating which color represents what. Other than that, everything looks good!
Approved.

**Comment by VaishaliThakoor** [comment]
Hey Thomas amazing work and analysis! I would just suggest you could add some description of what your code is doing after  the titles!

**Comment by VaishaliThakoor** [comment]
Approved!

**Review by VaishaliThakoor — APPROVED** [review]

**Pull request merged**
