### PR TITLE
Latest Milestone 1

### PR DESCRIPTION
**Pull request by TharushaCao**
Linear regression added 
Evaluated model
As required merged main into branch ( from web team announcement )

all details in commit messages.

Please check everything before accepting pull-request. Thank you

### CODE REVIEW

**Review by leakydishes — COMMENTED** [review]
Hi @TharushaCao -- can you add Web Leaders to review your code?

**Comment by leakydishes** [comment]
Appologies, I meant you need to add 2 reviewers to this code see top right hand side for people to review and approve :) -- As discussed in Week 4. Happy to review once you add a second person :)

**Comment by TharushaCao** [comment]
> Appologies, I meant you need to add 2 reviewers to this code see top right hand side for people to review and approve :) -- As discussed in Week 4. Happy to review once you add a second person :)

Added Rhuth as a second reviewer , will ask her if she is fine with reviewing the changes :)

**Review by leakydishes — COMMENTED** [review]
Hi @TharushaCao -- Please remove 'style guide for use case' and 'plot colour schemes' and 'function that extracts thte data form the JSON' check the template you only need your use case informaiton in markdown. in your mark down in Air quality Prediction'. Would recommend you add markdown to descripe what is happing in your code, you have comments so just copy these to markdown headings. In your last cell you have mark down with some results. Make this 'conclusion' or 'evaluation'. Use Case feels like it still has more to go when we don't conclude the last cell with Markdown. Check out Barrys use case in Repo to have a look at structure if you need  --- Do we need to merge test.txt? :) - Te'

**Pull request closed without merging**
