### PR TITLE
Data Science Team-Updated README.md file of Documentation folder.

### PR DESCRIPTION
**Pull request by RandiGunasekara**
Week4 - Pull request from Sprint 1

This pull request includes:
Renamed the use case name of 'Accessibility Analysis' Use case. 
Updated the README file to include all document names. 
Linked each document to its respective name in the README for improved accessibility. 
Ensured the README provides a comprehensive overview of the use case.

### CODE REVIEW

**Review by taehwan-jung — APPROVED** [review]
The readme file seems very well-organized. Thanks for your hard work!

**Review by Supratim-S220205268 — APPROVED** [review]
Hello Randi! Just had a look at the changes that you made. Great Work! The README file definitely looks a lot better now. Thanks for making things a lot simpler for us and students to come.

Keep up the good work! :)

**Comment by RandiGunasekara** [comment]
> The readme file seems very well-organized. Thanks for your hard work!

Hi @taehwan-jung , Thank you, I really appreciate your feedback!

**Comment by RandiGunasekara** [comment]
Hi @Supratim-S220205268 , Thank you so much! I'm glad the changes are helpful. I really appreciate your feedback!

**Pull request merged**
