### PR TITLE
Molliefernandez pedestriansafety

### PR DESCRIPTION
**Pull request by molliefernandez**
Completed within this Pull request:
- Deleted all old versions of pedestrian safety part 1 & part 2 use cases
- Uploaded the updated Pedestrian Safety Use case - new API, found the missing dataset and fixed path. (Still uses read.csv)
- Retired Pedestrian Safety part 2 as the additional dataset cannot be found and the use cases couldn't be combined because the only difference between them was the additional data set which I can't find.

### CODE REVIEW

**Comment by molliefernandez** [comment]
[Pedestrian Safety](https://trello.com/c/BnrtrtcU/196-pedestrian-safety)

**Comment by molliefernandez** [comment]
[Pedestrian Safety](https://trello.com/c/BnrtrtcU/196-pedestrian-safety)

**Comment by molliefernandez** [comment]
[New API - Melbourne Pedestrian Network Routes and Road Safety: Part 2](https://trello.com/c/Z7fITXbz/514-new-api-melbourne-pedestrian-network-routes-and-road-safety-part-2)

**Review by leakydishes — COMMENTED** [review]
Hey @molliefernandez -- good work. looks good. In Playground/ Pedestrian safety there is a README file which is empty. Could you delete this on your branch before merging? In Ready to publish Pedestrain safety (wrk_accident_pedestrians.loc[:,'DATAccidentDate_accident'].value_counts().) for inspecting accidents per day you may want to get mean/ medium counts per year and plot that. You have trends in here but the 1 & 2 number record counts is flooding your dataset in bar chart. Histogram
Screenshot 2024-03-31 at 12 26 49 pm
Also your number record count starts at 1, might be best to start at 0. Cause it look like there are zero on chart but its recording 1.

**Comment by molliefernandez** [comment]
I can't find the README file in that folder. In my branch it says that the folder has been removed.

In terms of the code I can change the graph but I didn't want to change any of the specifics because I didn't make the use case in the first place, I just made sure that it all worked.

**Review by leakydishes — APPROVED** [review]
@molliefernandez -- oh appologies i thought that was your graph, the markdown was very clean and tidy -- had your name all over it! README looks to be in the deleted pile now -- could have been my eyes and late nights. Approved.

**Comment by leakydishes** [comment]
@molliefernandez approved, you can merge pull request.

**Pull request merged**
