### PR TITLE
DATA SCIENCE TEAM - Route Planner - 100% completed

### PR DESCRIPTION
**Pull request by ChathuSatharasinghe**
- Adding description
- Adding Title
- Loaded data through API
- Fetching data
- Data Cleaning and Transformation
- Analysis
- Final Conclusion
- Adding references

### CODE REVIEW

**Review by dTitanium — CHANGES_REQUESTED** [review]
There is a conflict between your file name and the use case name inside the ipynb file
Put all libraries inside a single code chunk
Some of your graphs include NaN values.
Hide warnings from the outputs.

**Review by hiruboy96 — CHANGES_REQUESTED** [review]
Hi Chathumini,

In addition to the feedback provided by @dTitanium, please make the following changes to your use case:

1. **Error after "Correlation Analysis with Holidays and Weekends":** An error is occurring just after this section. To avoid coding errors throughout the notebook, it's recommended to always restart the kernel and run all cells to ensure everything runs smoothly from start to finish.

2. **Hide Warnings:** To make the notebook cleaner, use `warnings.filterwarnings('ignore')` to hide unnecessary warnings.

3. **API Key Visibility:** Your API key is currently visible in the code. Please refer to the code snippet provided in [this link](https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/usecases/ODSQL_API_v2_1_2024_tutorial_v2.ipynb) to hide your API key securely.

Let me know if you need any help with these changes!

Best regards,  
Venuka

**Comment by ChathuSatharasinghe** [comment]
Dear Dinuk and Venuka,

Thanks for the comments on working as per the requested changes I do the necessary changes as mentioned.
Please check and confirm.


Thanks

**Review by hiruboy96 — APPROVED** [review]
Well done!

Good luck for the next trimester!

Regards,
Venuka

**Review by dTitanium — APPROVED** [review]
great work!

**Comment by ChathuSatharasinghe** [comment]
Dear Dinuk & Venuka,

Thanks for the support

**Pull request merged**
