### PR TITLE
Pranjal

### PR DESCRIPTION
**Pull request by pranjalsingh3**
Header and Footer Design Proposition V2
Also Includes: 
1. Colour Scheme
2. Font Style 
3. Top Button Feature
4. Button Type
5. Logo Hyperlink

### CODE REVIEW

**Comment by SijuDENG** [comment]
According to the request of the web team, closed

**Comment by pranjalsingh3** [comment]
I’m sorry what is this about?

**Comment by SijuDENG** [comment]
The web team has submitted the final team document. The pull made 2 weeks ago is now considered defective. Now close all pull requests from two weeks ago.

**Comment by SijuDENG** [comment]
The web team submitted a pull yesterday that included all of the web team's work.

**Pull request closed without merging**
