### PR TITLE
add validation of all input in contact us form

### PR DESCRIPTION
**Pull request by allengao19**
Add validation of all inputs in contact us form. 
Screenshot 2024-05-07 at 12 53 23

If there's an error previously, validate again and clear if resolved.
Screenshot 2024-05-06 at 17 16 14

### CODE REVIEW

**Review by kaseyuu — CHANGES_REQUESTED** [review]
Hi Allen, the validations look great. Can you also add validation so that the name and message parts cannot be blank?

**Comment by allengao19** [comment]
@kaseyuu I have added the validations of all inputs. Please review.

**Review by kaseyuu — APPROVED** [review]
All good!

**Comment by allengao19** [comment]
[Contact page form (max1)](https://trello.com/c/24sVIILx/542-contact-page-form-max1)

**Pull request merged**
