### PR TITLE
Data Science Team: Analyzing and Forecasting Tree Canopy Loss in the City of Melbourne (100%) and Parking Availability Near Places of Interest in Melbourne (100%)

### PR DESCRIPTION
**Pull request by Samiha-Haque**
Hello @VaishaliThakoor and @HarshDW09,
I have completed both my use cases and put them in Ready to publish T2 2024 and removed my folder from Playground. 

In the Tree canopy use case you will find 2 additional map files (html) which needed to be saved as html otherwise, the size of my code file was crossing GitHub's file limit. I have however linked the map files within my notebook.

Both my use cases are too large to be displayed on GitHub but the limits are fine to be uploaded and stored in GitHub. To view them you can visit https://nbviewer.org/ and paste the links to the ipynb files. 

Thanks.

### CODE REVIEW

**Review by HarshDW09 — COMMENTED** [review]
Hi @Samiha-Haque ,

I just wanted to quickly check if the link to the map, "Decrease in tree canopy coverage from 2018 to 2021," is working correctly in your document under the Analysis of tree canopy areas: distribution, transformation, and correlation section. Please let me know if it is visible for other reviewers. If not, no worries!

For the second use case, it would be great if you could add a little more comments/Description below the headings. I believe it would provide additional clarity.

**Comment by Samiha-Haque** [comment]
Hi @HarshDW09 
Thanks for the feedback. I added more descriptions under each title in the Parking Availability use case. For the Tree canopy one, I think you can access it, try using  https://nbviewer.org/ and open the use case. Clicking the links should display the maps on nbviewer as well.

**Review by HarshDW09 — APPROVED** [review]
Samiha All good !

**Review by VaishaliThakoor — COMMENTED** [review]
Hey Samiha! Amazing work on both use cases! For the use case **Analyzing and Forecasting Tree Canopy Loss** - I can see 2 html files and one is -Decrease_in_tree_canopy_coverage_from_2018_to_2021.html - is this an output from your use case code? I tried opening it and it kept loading even in nbviewer.
Also with the rest of the files which is your ipynb, json and HTML files for your usecase the names of the files are a little confusing as they all have "ipynb" in them for example "Analyzing and Forecasting Tree Canopy Loss in the City of Melbourneipynb.json" 

Otherwise all good to go!

**Comment by Samiha-Haque** [comment]
hi @VaishaliThakoor  Thanks for the feedback and pointing it out that the file names had ipynb, I did not notice that. I fixed the file names. The maps take a little longer to load on nbviewer, it usually shows up eventually. I cannot display them within the ipynb file since the size of the file increases and cross the limit of GitHub. Hence I stored them outside and linked them within the notebook. They load on my end through nbviewer but takes a while.

**Comment by VaishaliThakoor** [comment]
All good then! @Samiha-Haque

**Pull request merged**
