### PR TITLE
Abhishek repsonsive menu

### PR DESCRIPTION
**Pull request by abhishek-chiluka99**
WD_FrontEnd_Abhishek_Chiluka_PR3

- Completed building the responsiveness of the menu.
- Used the same design as Figma.
- Used the responsiveness of the Bu
image
rger menu

### CODE REVIEW

**Comment by Sakif-Hasan** [comment]
Review the merge conflict in the component : Header.

**Comment by abhishek-chiluka99** [comment]
Sakif, which line of the code causing merge conflict, could you please guide me.

**Comment by Sakif-Hasan** [comment]
The tailwind CSS for your header. Please attach screenshot of your build for full screen view and mobile view.

**Comment by abhishek-chiluka99** [comment]
Home page: Website mode.
image

Mobile view
image

**Comment by kaseyuu** [comment]
image
please resolve the conflicts using command line as suggested

**Review by kaseyuu — CHANGES_REQUESTED** [review]
Hi Abhishek did you change the styling of header for large screens? the margins/ paddings on the left and right are gone and logos are so close to screen side now. Could you please keep the header as before for large screen and only adjust responsive menu for phone screen? Thanks!

**Review by kaseyuu — APPROVED** [review]
Looks all good now

**Pull request merged**
