### PR TITLE
DS Smart Bin and Disposal Optimisation repointing API(file deletion)

### PR DESCRIPTION
**Pull request by Samiha-Haque**
Hi @leakydishes and @TharushaCao 
I am deleting the original file from the "UPDATE NEEDED" folder as this usecase was rewritten as "Waste Analysis" and merged to main today.

### CODE REVIEW

**Comment by TharushaCao** [comment]
@Samiha-Haque where is the 'merged to main today' located atm?

**Comment by Samiha-Haque** [comment]
@TharushaCao in Ready to publish folder T1 2024: https://github.com/Chameleon-company/MOP-Code/tree/master/datascience/usecases/READY%20TO%20PUBLISH/T1%202024/Waste_Analysis

I completed the rewrite and API repoint of this usecase and had renamed it Waste Analysis

**Review by leakydishes — APPROVED** [review]
All good thanks! @Samiha-Haque - you can merge.

**Comment by Samiha-Haque** [comment]
[New API - Smart Bin and Disposal Optimisation](https://trello.com/c/wSC2GMxN/516-new-api-smart-bin-and-disposal-optimisation)

**Pull request merged**
