### PR TITLE
Bree m branch

### PR DESCRIPTION
**Pull request by breemclennan**
Pedestrian road safety use case part 1 and EDA

### CODE REVIEW

**Comment by jackpham206** [comment]
Comprehensive EDA with interesting mapping coming along with different plotting.

**Comment by jackpham206** [comment]
It looks good to me but I'm not sure if this needs Mollie to approve

**Comment by jackpham206** [comment]
Hi Hannah. It looks good to me but I'm not sure if this needs Mollie to approve.

**Comment by jackpham206** [comment]
@hannahsm1th done. Let me know if there are issues :D. Thanks Hannah.

**Review by hannahsm1th — APPROVED** [review]

**Pull request merged**
