### PR TITLE
pedestrian and bustops 80% complete

### PR DESCRIPTION
**Pull request by remmzytom**
Data manipulation and analysis using pandas
Advanced visualization techniques with matplotlib and geopandas for geospatial data analysis.
Spatial analysis using geopandas to understand geographic relationships between pedestrian activity and bus stop locations.
Implementation and interpretation of clustering algorithms for identifying spatial patterns in data.

needs to be done
Integration of machine learning techniques (such as clustering) with spatial analysis to derive actionable insights for urban planning.
Application of data-driven decision-making processes in urban planning contexts.ntexts.

### CODE REVIEW

**Comment by molliefernandez** [comment]
Great work so far, a fantastic start to your use case! A few comments:
- Please rename your use case file to reflect the use case name rather than "my project"
- Please go through and give everything a proof read there were quite a lot of errors and some things that needed to be reworded.
- I would love to see more of the written aspects within the code about what you are doing and how you are manipulating the data, rather than just what the results are. Remember this is meant to be a **tutorial** for someone to follow and understand why you are doing each step.
- Don't forget to remove the "style guide" at the start of the use case.

**Comment by TharushaCao** [comment]
Like Mollie said please rename the use case ipynb name  and reference it in the description on what the other files are too

**Review by molliefernandez — APPROVED** [review]
Great work so far, a fantastic start to your use case! A few comments:
- Please rename your use case file to reflect the use case name rather than "my project"
- Please go through and give everything a proof read there were quite a lot of spelling errors and some things that needed to be reworded.
- I would love to see more of the written aspects within the code about what you are doing and how you are manipulating the data, rather than just what the results are. Remember this is meant to be a **tutorial** for someone to follow and understand why you are doing each step.
- Don't forget to remove the "style guide" at the start of the use case.

**Review by TharushaCao — APPROVED** [review]

**Comment by AliColli** [comment]
Hi, your pull request has been approved by two people. Please return to the pull request and press the merge pull request button :)

**Pull request merged**
