### PR TITLE
Arjun Bird Analysis Final

### PR DESCRIPTION
**Pull request by 13dothraki**

### CODE REVIEW

**Comment by TharushaCao** [comment]
All good @13dothraki . From previous pull request you had an error so this is the v2 branch , will be closing previous pull request

**Review by TharushaCao — APPROVED** [review]

**Review by AliColli — APPROVED** [review]
Looks good to me, folders all good :)

**Comment by AliColli** [comment]
@13dothraki ready for you to merge :)

**Review by RhuthK — CHANGES_REQUESTED** [review]
Hi Arjun good work on the use case. I would personally expect the following changes to be made. 
1) Please add a few user stories related to your use case. 
2) Good explanation on code blocks. I would suggest comment more on the performance metrics for example: What does the mean absolute error value of 59.96 tell us? what is its significance? and so on. 
3) Conclusion and Reference section is missing. Please consider adding those. 

I will approve the pull request once these changes are made. :)

**Pull request closed without merging**
