### PR TITLE
Data Science Team: Parking Slot Occupancy Detection for on street parking: %35 Complete    

### PR DESCRIPTION
**Pull request by sgulluoglu**
use case proposal
scenario
restrictions of the study 
read data file using API
read dataset in csv file
commencing data preprocessing
finding/filling-matching missing values
converting time zone
splitting/adding new columns
change variable type of some columns/assign integer values
calculations 
create processed csv file
dataset is ready for further analysis

### CODE REVIEW

**Comment by Sachithak95** [comment]
Hi @sgulluoglu ,

There is a file outside your playground folder. Please delete that folder and do a new pull request.
Please do let me know if you need any support.
Thank you!

**Review by Sachithak95 — CHANGES_REQUESTED** [review]
@sgulluoglu 

Please rename the use case template name accordingly with your use case name.
Alos in your code the formatting's are not done properly so please do adjust them as well.

Thank you!

**Review by Sachithak95 — APPROVED** [review]
HI @sgulluoglu ,

Great work!
your work is ready to merge and after merging you can start your sprint 2.
Please go through the previously finished use cases and get an idea to improve your formatting and structuring.

Thank you!

:)

**Review by Sabihulhassan98 — APPROVED** [review]
Well done @sgulluoglu ,
Your work looks good although formatting and structure can be improved. please go ahead and merge this use case

**Comment by sgulluoglu** [comment]
> Well done @sgulluoglu , Your work looks good although formatting and structure can be improved. please go ahead and merge this use case

Thank you for your time and effort, I will definitely adjust the formatting in the sprint2.

**Pull request merged**
