### PR TITLE
DS _ Public Transport Accessibility to Business Location Usecase 100% Complete and Impact of Coworking Spaces on Social Wellbeing Indicators 100% Complete 

### PR DESCRIPTION
**Pull request by VaishaliThakoor**
Hi @Samiha-Haque and @HarshDW09 
I have added both of my completed use cases to ready to publish and I have also deleted my folder in playground.
The Public Transport Accessibility use case is big due to the datasets being big and so the maps might not load on GitHub but it can viewed on nbviewer.
Both use cases have been completed and I would be grateful for your review!

### CODE REVIEW

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi @VaishaliThakoor , the use cases look great! However, I noticed a few minor issues:
1. In Public Transport Accessibility, the table in code block 22 has '<center><table><tr><th colspan='2' align='center' instead of descriptions.
2. It would be great if legends and titles could be added to the maps of both use cases. Also easier to present in Innofes too!

**Comment by VaishaliThakoor** [comment]
Hey @Samiha-Haque and @HarshDW09 I made the changes requested! Please let me know if it is all good now! Thank you guys!

**Review by Samiha-Haque — APPROVED** [review]
Hey @VaishaliThakoor , the maps don't have titles but everything else looks good!
I am approving it.

**Review by HarshDW09 — APPROVED** [review]
Looks Good !

**Pull request merged**
