### PR TITLE
DS API repoint Liveability analysis Dependency 

### PR DESCRIPTION
**Pull request by Samiha-Haque**
Hi @molliefernandez and @TharushaCao I am trying to do API repointing of Liveability Analysis usecase which had a dependency dataset. I moved it to the DEPENDENCIES folder.

### CODE REVIEW

**Comment by molliefernandez** [comment]
Looks Good @Samiha-Haque, maybe change the name of the file to include the use case it is associated with. Or even put it in a folder with the use cases name as well as changing the file name so we know exactly what it is for.

**Review by molliefernandez — CHANGES_REQUESTED** [review]
Looks Good @Samiha-Haque, maybe change the name of the file to include the use case it is associated with. Or even put it in a folder with the use cases name as well as changing the file name so we know exactly what it is for.

**Comment by TharushaCao** [comment]
Looks good , apart from changes from mollie all good

**Review by TharushaCao — APPROVED** [review]

**Comment by Samiha-Haque** [comment]
hi @molliefernandez and @TharushaCao, I hope the above commits are good to be merged?

**Pull request merged**
