### PR TITLE
Enhancing Pedestrian Safety in Melbourne's Urban Areas - DS  Changed 

### PR DESCRIPTION
**Pull request by dTitanium**
@molliefernandez 
Corrected description typo
Added Description for each code 

@leakydishes

### CODE REVIEW

**Comment by dTitanium** [comment]
[New Use Case - Enhancing Pedestrian Safety in Melbourne's Urban Areas](https://trello.com/c/qDby8CZE/434-new-use-case-enhancing-pedestrian-safety-in-melbournes-urban-areas)

**Comment by TharushaCao** [comment]
This pull request will be closed soon, as discussed in teams we need to change how you added the repo

**Comment by TharushaCao** [comment]
To be deleted at EOT :)

**Comment by dTitanium** [comment]
[New Use Case - Enhancing Pedestrian Safety in Melbourne's Urban Areas](https://trello.com/c/qDby8CZE/434-new-use-case-enhancing-pedestrian-safety-in-melbournes-urban-areas)

**Pull request closed without merging**
