### PR TITLE
Use case updated

### PR DESCRIPTION
**Pull request by carissawong**
Use case updated (user story, background, and conclusion), added more visualisation, include static plots to see if they can be displayed properly on GitHub

I deleted branch and created a new one, fetched origin and am trying to push again. I hope it works.

### CODE REVIEW

**Review by AliColli — COMMENTED** [review]
Hi Carissa, looking in good shape. Just a couple of things - You can delete the first type of data import and just leave the one that Te Claire developed, only need to import code one way. The scatterplot doesn't show as the call for it is commented out. All of the plots that do not say "static" at the top are not rendering on GitHub. Also the static tree map is not working.

**Comment by carissawong** [comment]
Hi Alison, thanks for feedback! I will soon finalize the use case by removing all unnecessary comments, code, redundant texts, and plots. This push, if approved and merged, primarily aims to serve as evidence for my onTrack task and to ensure that my plots (both interactive and static versions) display correctly on GitHub.

**Comment by leakydishes** [comment]
Hi @carissawong we will discuss how to push code to published folder and what files are required. If you want to get a head start have a look in documentation for details. Sprint 3 we aim to have all the code in published directory. No point creating multiple publishing files with required html if people are still updating.

**Comment by leakydishes** [comment]
Can you make the fixes Ali was talking about. If you need additional help we can go through your code in the mop meeting. Difficult supporting members over messages to help fix code. Remember you don't need your code merged with main to be reviewed with mentor. You only need merged evidence for repo - we expect students to make 1 pull request for each sprint. Next Retro Individual assessment is due end of next month 10.1 where you will need merge evidence.

**Comment by carissawong** [comment]
Hi @leakydishes, I have revised the code according to your recommendations and removed any unnecessary code and text.

**Review by AliColli — APPROVED** [review]
Hi Carissa, the second file in files changed loads al the images perfectly on https://nbviewer.org/, even the tree diagrams etc. 
Great to see other API methods removed. 
Explanation of figures and tables is well done.
 Maybe consider adding a final overall summary section? 
Otherwise looks good to me.

**Comment by carissawong** [comment]
Hi @AliColli

Definitely! I will add a final overall summary to the use case. However, I'm wondering if I should wait for the next sprint to push the changes, since Te mentioned that we are expected to have three pull requests in total. Since you have already approved my current pull request, should I merge it now and wait for the next sprint to include the overall summary? Or if I can complete it before the Sprint 2 push deadline, can I still push changes now and merge everything at once?

**Pull request merged**
