### PR TITLE
DATA SCIENCE-Accessibility analysis (diversity, inclusion, persons with disabilities/impairments)-90% complete

### PR DESCRIPTION
**Pull request by RandiGunasekara**
Week 3 pull request for review from Sprint 1

Use case includes:
Use case introduction and objectives.
Import datasets using API v2.1 GET requests with /exports extension.
Filtering and cleaning of data for accessibility analysis.
Splitting geographical coordinates into latitude and longitude.
Renaming columns for better readability and usability.
Filtering data based on specific criteria (e.g., accessible facilities, steep footpaths).
Distance calculations to analyze proximity between facilities.
Creation of maps using Folium to visualize:
Underserved areas with recommended zones for public facilities.
Dynamic mapping of available public toilets, train stations, and footpaths.
Bar and pie charts for visual representation of accessibility metrics.
Generating future recommendations based on analysis to improve accessibility planning.

### CODE REVIEW

**Review by taehwan-jung — COMMENTED** [review]
Hi @RandiGunasekara,  great work!
Just one small thing — I noticed the API key is visible in the file. 
Other than that, everything looks fantastic.
Also, great job organizing the files!

**Review by Supratim-S220205268 — COMMENTED** [review]
Hi Randi, this is amazing work! I really like the fact that you've chosen a use case that relates to accessibility and wellbeing. I haven't seen a lot of use cases addressing such issues, so I'm glad you're working on this.  Your visualization part looks great as well, especially the parts where you've used folium. I hope you can give me a few tips on how to do that myself :)

Apart from all your good work, just two things that I wanted to check with you. Firstly, just like Taehwan called out, your API key is visible. Secondly, just wanted to know about the rest of your commits where you've renamed some files. Is this part of the leadership task that you were working on?

**Comment by RandiGunasekara** [comment]
> Hi @RandiGunasekara, great work! Just one small thing — I noticed the API key is visible in the file. Other than that, everything looks fantastic. Also, great job organizing the files!

Hi Taehwan, Thanks for the review. Yeah I just missed removing the API , I will update it and commit again, Thank you!

**Comment by RandiGunasekara** [comment]
> Hi Randi, this is amazing work! I really like the fact that you've chosen a use case that relates to accessibility and wellbeing. I haven't seen a lot of use cases addressing such issues, so I'm glad you're working on this. Your visualization part looks great as well, especially the parts where you've used folium. I hope you can give me a few tips on how to do that myself :)
> 
> Apart from all your good work, just two things that I wanted to check with you. Firstly, just like Taehwan called out, your API key is visible. Secondly, just wanted to know about the rest of your commits where you've renamed some files. Is this part of the leadership task that you were working on?

Hi @Supratim-S220205268  Thanks for the review! Yes I missed out removing my API key , I will remove it now and update the code. And also yes the renamed files are a part of my leadership task, which is to organize the documentation folder. Thank you!

**Review by taehwan-jung — APPROVED** [review]

**Review by Supratim-S220205268 — APPROVED** [review]
Hey Randi! The changes made for the leadership task look good as well. Just try to keep our mentor as reviewer going forward for such tasks just like we discussed.

Great work! Happy to Approve!

**Pull request merged**
