### PR TITLE
DATA SCIENCE TEAM - Tree History - 100% Complete

### PR DESCRIPTION
**Pull request by hiruboy96**
**_Use case completed_**

Use case includes:

- Adding Description
- Adding Title
- Loaded Data through API
- Removing Unwanted columns
- Renaming columns to match the other dataset
- Historical vs. Current Species Diversity (Venn Diagram)
- Change in Species Abundance Over Time
- Geographical Distribution of Trees (Map Visualization)
- Time-Series Analysis of Tree Planting
- Habitat Analysis for Pre-Colonial Species
- Ecological Dynamics of Tree Species in Parks vs. Streets in Melbourne
- Adding filters to the map
- Timeseries Model Fitting (ARIMA Model Forecasting)
- Forecasted tree plantings for the future 5 years
- Updated the API to catch the data by hiding the API key using Environment Variable.
- Finalizing the use case by achieving the desired outcome.
- Completed use case write-up
- Modified codes with explanations of outcomes
- Added conclusion and final thoughts based on the outcomes
- Added references

### CODE REVIEW

**Comment by hiruboy96** [comment]
[Tree History](https://trello.com/c/aWVrUG1r/442-tree-history)

**Review by AliColli — APPROVED** [review]

**Comment by hiruboy96** [comment]
@AliColli  @HarleyNgo Hi, I've uploaded the relevent JSON and HTML files for the review.
Thank you in advance. :)

**Review by HarleyNgo — CHANGES_REQUESTED** [review]
Hi Venuka!
Please move the 3 files to READY TO PUBLISH then create the pull request again.

**Review by AliColli — CHANGES_REQUESTED** [review]
3 files look great, make sure you move your use-case into READY TO PUBLISH and I will approve :)

**Review by HarleyNgo — CHANGES_REQUESTED** [review]
- 3 files of use case should be put in 1 folder, with folder name is the use case name. location of folder is datascience/usecases/READY TO PUBLISH.
- Document of Using Folium should follow this format [LINK](https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/documentation/Documentation%20template.dotx), and should be put in folder /documentation with 2 file version .docx and .pdf
- remove file Smart Bin or move it to UPDATE NEEDED if it's not done.
- remove venuka.txt as it's not needed

**Review by HarleyNgo — APPROVED** [review]

**Review by AliColli — APPROVED** [review]

**Pull request merged**
