### PR TITLE
Arjun (Bird Sightings Data Analysis on Geo data of Bird Sightings- NOT COMPLETED YET)

### PR DESCRIPTION
**Pull request by 13dothraki**
Bird Sightings Data Analysis on Geo data of Bird Sightings

- latest changes to usecase
- Added one more dataset 
- combined two dataset
- Not yet completed whole project

### CODE REVIEW

**Review by TharushaCao — COMMENTED** [review]
- Can you please add some wording or explanation ( markdown writing )

**Review by twar9432 — APPROVED** [review]
The maps are looking good, I'd continue to work on adding in the weather dataset and beginning the analysis/prediction components.

**Review by TharushaCao — APPROVED** [review]
continue working on this use case to the best of your abilities. again reminder to have markdown notes explaining necessary sections.

**Review by AliColli — APPROVED** [review]

**Comment by AliColli** [comment]
@13dothraki code has been reviewed and ready for you to press merge pull request button 👍

**Comment by leakydishes** [comment]
Hi @ 13dothraki
This branched faced an error. You need to 'rebase' with main and then pull request. Reach out if you need any help. Review 'onboarding documentation' which goes through these steps.

**Pull request closed without merging**
