### PR TITLE
Live Music Events Use Case for Review

### PR DESCRIPTION
**Pull request by molliefernandez**
Live Music Events Use Case 
Rough finished draft, needs a bit of fine tuning

### CODE REVIEW

**Comment by molliefernandez** [comment]
[DS New Use Case - Live Music Event Planning](https://trello.com/c/G2ARpN3n/477-ds-new-use-case-live-music-event-planning)

**Review by leakydishes — APPROVED** [review]
@molliefernandez looks good - you might want to put some interactive controls in for part 2. This is a good reference to use -- https://towardsdatascience.com/interactive-controls-for-jupyter-notebooks-f5c94829aee6

**Comment by leakydishes** [comment]
@molliefernandez approve, you can merge pull request.

**Comment by molliefernandez** [comment]
Thank you, I will look at that!

**Pull request merged**
