### PR TITLE
Molliefernandez bicycle network safety part 2

### PR DESCRIPTION
**Pull request by molliefernandez**
- Updated API
- Updated Dependencies
- Removed old versions
- Uploaded to ready to publish T1 2024

### CODE REVIEW

**Comment by molliefernandez** [comment]
[New API - Bicycle Network Routes and Road Safety Part 2](https://trello.com/c/5ynqmMWS/193-new-api-bicycle-network-routes-and-road-safety-part-2)

**Comment by molliefernandez** [comment]
[Dependency Updates](https://trello.com/c/evMmzFTW/532-dependency-updates)

**Review by leakydishes — APPROVED** [review]
Looks good @molliefernandez

**Comment by leakydishes** [comment]
Approved @molliefernandez you can merge.

**Pull request merged**
