### PR TITLE
Manasa

### PR DESCRIPTION
**Pull request by Manasa-n1**
Week 8 Pull request for review from sprint 2
Use Case Includes:
- Use case Introduction.
- Import data using API
- Filtering of DataFrames
-  Cleaning and preprocessing of the Dataset. 
- Exploratory Data Analysis for Jobs per ANZSIC for blocks and House Prices by Small Area - Sale Year and  House Prices by Small Area - Sale Year
- Box plot , histogram plot , Bar chart to identify variable relationship
- Combining all Visualisations and Data
- Use of heatmap shows the correlation coefficients between various features
- Linear Regression for predictive analysis
- Random forest for predictive analysis

### CODE REVIEW

**Comment by HarleyNgo** [comment]
Great work! 
A few small things to improve:
- Chart Total jobs in block by Regions: rotate the x-labels for better visual
- Remove un-used code block at the end
- Add headers before each part/chart so that the user can follow easier

**Review by HarleyNgo — CHANGES_REQUESTED** [review]
hope my comments help!

**Review by AliColli — COMMENTED** [review]
@Manasa-n1  I will review after you add updates :)

**Comment by Manasa-n1** [comment]
Worked as per the comment and hence need to pull request again for review and closing this pull request

**Pull request closed without merging**
