### PR TITLE
Data Science - Air Quality Based on Environmental Factors - 100%

### PR DESCRIPTION
**Pull request by alireza-montazeri**
Week 10 pull request for review from sprint 3:

* Added data preprocessing and cleaning logic for microclimate and Argyle air quality datasets.
* Performed feature importance analysis to identify key factors influencing air quality.
* Implemented LSTM and GRU models for air quality prediction using PM2.5 and PM10 data.
* Included additional environmental factors (temperature, humidity, wind) in model development.
* Resampled and normalized datasets to ensure consistency for time-series modeling.
* Developed two approaches: historical data-based and environmental factor-based predictions.
* Compared model performances and calculated test loss for both approaches.
* Visualized real vs. predicted values for both models.
* Updated project description, references, tags, and technology stack.
* Generated and added .ipynb, .html, and .json files to the READY TO PUBLISH use cases for T2 2024.
* Removed my folder from the playground directory.

### CODE REVIEW

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi @alireza-montazeri, the forecasting looks good and the 3 files are perfect.
However, some minor changes are required:
1. Add a title and legend to your both your maps

**Comment by alireza-montazeri** [comment]
Hi @Samiha-Haque, Thanks for the feedback. I added title and legend to both maps and generated the HTML file again.

**Comment by alireza-montazeri** [comment]
Hi again @Samiha-Haque. I made the changes and am waiting for your approval.

**Review by Samiha-Haque — APPROVED** [review]
@alireza-montazeri Great work! Approved.

**Comment by HarshDW09** [comment]
Looks Good!

**Pull request merged**
