### PR TITLE
weather classification use case completed 100%

### PR DESCRIPTION
**Pull request by remmzytom**
At broad Level

In this project, I developed a model that can predict weather conditions using key environmental data such as temperature, humidity, air pressure, and pollution levels. The model was tested and showed strong accuracy in its predictions, meaning it can be trusted to provide reliable insights about upcoming weather.

I saved the model so it can be easily reused in future applications without needing to retrain it. I also tested it with different sets of data to ensure it works as expected.

This solution can help organizations in industries like agriculture, construction, and event planning, where weather conditions are important for making decisions. By accurately predicting weather conditions, businesses can plan more efficiently, avoid risks, and make better decisions. This model is ready to be integrated into systems that help make informed decisions, and it can be further improved as more data becomes available.

### CODE REVIEW

**Review by trostov — COMMENTED** [review]
Hello Akintomiwa, your title mentions your usecases are 100% completed, which assuming you want to publish them, they should be in datascience/ready to publish/t2 2024 folder instead of playground

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi @remmzytom , the usecase looks good. However there are a few changes which are required:
1. There are a few empty cells within the notebook, maybe remove them
2. Import all the libraries and packages at the very beginning of the file and not in-between multiple times.
3. Your json file says "advanced" but your code file says "intermediate" please fix the level value and select either one.
4. If the .pkl file is not required then please delete it.
5. Your function list is missing the json and html file.
6. Your function documentation should follow the MOP documentation template and you need to upload the documentation in the "documentation folder" instead. 
Link to template: https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/documentation/Documentation%20template.dotx
Link to documentation folder: https://github.com/Chameleon-company/MOP-Code/tree/master/datascience/documentation 
You need to upload both .pdf and .doc file
7. Your house proces and landmark use case and Pedestrian counts and bus stops both exist in the master "UPDATE NEEDED" folder from last trimester. Please remove them since they are already on GitHub.
8. There is a "Bus and Pedestrian Analysis" in the T2 2024 folder which was uploaded 1 month ago: https://github.com/Chameleon-company/MOP-Code/tree/master/datascience/usecases/READY%20TO%20PUBLISH/T2%202024/bus%20and%20pdestrian%20analysis 
Is this the same file as the Pedestrian counts and bus stops. If it is then please remove Pedestrian counts and bus stops from "UPDATE NEEDED" since it's already published.

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi @remmzytom, I noticed the changes, 
The pedestrian counts and bus stops and landmarks house prices don't have all the 3 files (html, json and ipynb). If you updated API, they need to be moved from UPDATE NEEDED to READY TO PUBLISH T2 2024. Also Landmarks and house prices code block 231 does not use API 2.1v and and you can removed code block 232.
I noticed a file in Ready to publish "bus and pedestrian analysis" - I am not sure if they are updated or you are doing the API again? It is missing the html file as well. Maybe @francisrusli  and @trostov can help understand.

Also if you make updates, please use @ to the reviewers so that they get notification. Otherwise, the changes might not be reviewed in time.

**Comment by remmzytom** [comment]
All has been fixed has requested @Samiha-Haque  @trostov @francisrusli

**Review by trostov — APPROVED** [review]
checked as per Samihas last comments
pedestrian counts/bus stops contains all 3 files, in T2 2024.
landmarks/house prices uses 2.1
francis pointed out that the single html file looks to be an update, with other files already in master

**Review by francisrusli — APPROVED** [review]

**Review by Samiha-Haque — APPROVED** [review]

**Pull request merged**
