### PR TITLE
DATA SCIENCE Small Area Population Growth & Active Transportation usecase - 100% Complete

### PR DESCRIPTION
**Pull request by RhuthK**
Still in progress. Few new models to add and it will be finished by week 9. 

Thank you for reviewing in advance.

### CODE REVIEW

**Review by molliefernandez — CHANGES_REQUESTED** [review]
Your code cannot be merged because your branch has conflicts, please address this and re create the pull request

**Comment by TharushaCao** [comment]
Please reduce or remove the HTML maps and try to output them on the use case itself. Thank you

**Review by TharushaCao — APPROVED** [review]
Good Use case , remember to add to ready to publish if fully compleated .

**Review by AliColli — CHANGES_REQUESTED** [review]
Use case looks great! Pop it into the ready to publish folder and push again, then I will approve :)

**Review by molliefernandez — APPROVED** [review]
Love how you have laid it out in steps and explained the whole way what you are doing and why. 
A couple of things to note / fix:
- There's a lot of spelling errors that need to be fixed for example you seem to be using American English with "optimize" when it should be "optimise" or "analyze" should be "analyse" etc.. (I'm only being picky because it is for the City of Melbourne, an Australian city so it should be in Australian English)
- Also is 300 hours an accurate time for how long it will take someone to run through the whole use case?? Normally people put a couple of hours at most.....

**Comment by leakydishes** [comment]
Hi @RhuthK 

You need to do the following ASAP
1. Move your files to a new directory in 'READY TO BE PUBLISHED'
2. Delete your old directory in PLAYGROUND. 
3. Re-request Pull request 
4. After you have been re-approved you can then merge pull request. 
Thank you.

**Review by AliColli — APPROVED** [review]

**Pull request merged**
