### PR TITLE
Add time series model analysis

### PR DESCRIPTION
**Pull request by jenniferyau**

### CODE REVIEW

**Review by SijuDENG — CHANGES_REQUESTED** [review]
You created a file in usecases/playground with no format and empty content. Can you explain it?

**Comment by jenniferyau** [comment]
> You created a file in usecases/playground with no format and empty content. Can you explain it?

Yes, I want to create the empty file first and once I use the template combine all the files then can upload to this file.

**Comment by SijuDENG** [comment]
That folder is working for unfinished case which will transfer to next semester.

**Comment by SijuDENG** [comment]
Regardless of transfer or ready publish, only moving files. Working only in personal folders.

**Comment by jenniferyau** [comment]
But I think you have removed my previous pull request already, this one is add new file (time series analysis in my personal playground) ?

**Pull request closed without merging**
