### PR TITLE
add the submit button and update css to TailwindCss

### PR DESCRIPTION
**Pull request by allengao19**
Screenshot 2024-04-21 at 22 00 23

### CODE REVIEW

**Comment by kaseyuu** [comment]
Hi Allen you may want to adjust the responsiveness of the title because on my wide screen, it looks wired.

**Review by kaseyuu — CHANGES_REQUESTED** [review]
Hi Allen you may want to adjust the responsiveness of the title because on my wide screen, it looks wired.

**Review by kaseyuu — APPROVED** [review]
All good now!

**Comment by allengao19** [comment]
[Contact page form (max1)](https://trello.com/c/24sVIILx/542-contact-page-form-max1)

**Pull request merged**
