### PR TITLE
Smart Bin Optimized Waster Collection Route (100% Complete )

### PR DESCRIPTION
**Pull request by Sachithak95**
Hi !

Can you please review my pull request. This use case is fully completed (100%).

Branch Name: Sachitha-K

Note: Due to the large size of this file, it is recommended to download and execute the code on your local machine. Ensure you have Jupyter Notebook installed as a prerequisite.

Thank you!
Sachitha.

### CODE REVIEW

**Comment by Sachithak95** [comment]
[New Use Case - Smart Bin Optimized Waster Collection Route](https://trello.com/c/Mc3jKkm7/305-new-use-case-smart-bin-optimized-waster-collection-route)

**Review by AliColli — APPROVED** [review]
Super explanations of why you chose your methodology. Use case looks completed to me, just a couple of small errors in the first sentence of the user story (spaces after commas and a capital s). I like the map with the route, very clear you have an outcome for your usecase. I also checked over documentation for Distance Matrix and PowerBI startup guide - clear instructions and great screenshots.
The use case opens fine in https://nbviewer.org/ for reviewing without needing to download :)

**Review by HarleyNgo — APPROVED** [review]

**Comment by Sachithak95** [comment]
Hi both,
@AliColli @HarleyNgo 

I have done the final amendments after your review from the second pull request.

Can you please review my final request. This use case is fully completed (100%).

Branch Name: Sachitha-K

Note: I have also added the .json and .html for my use case.

And after this review I believe that I can merger this to the main branch! 

Thank you!
Sachitha.

**Review by AliColli — APPROVED** [review]
:)

**Review by HarleyNgo — APPROVED** [review]

**Comment by leakydishes** [comment]
Hi @Sachithak95 you need to merge this pull request ASAP

**Comment by Sachithak95** [comment]
[New Use Case - Smart Bin Optimized Waster Collection Route](https://trello.com/c/Mc3jKkm7/305-new-use-case-smart-bin-optimized-waster-collection-route)

**Pull request merged**
