### PR TITLE
MOP_WD_Mihir_Dobariya#PR2

### PR DESCRIPTION
**Pull request by md0311**
Responsiveness on footer along with made changes in dashboard it was not suitable for footer to complete before it. So it was necessary to change in dashboard for responsiveness.

### CODE REVIEW

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
Please resolve the merge conflict in the home page

**Comment by md0311** [comment]
> Please resolve the merge conflict in the home page

please can you drop image for same it will bw really helpful to solve

**Comment by md0311** [comment]
> > Please resolve the merge conflict in the home page
> 
> please can you drop image for same it will bw really helpful to solve

just had look of problem seems like this is beacuse when i made changes for it some part of code was not merged after merging new PR it has conflict. Great working on it solve.
please if you can send me image of conflict that will be surely pleasure to me for correcting it.

**Comment by Tyrepo1** [comment]
If you pull from master again itll show you the conflict

**Comment by md0311** [comment]
> If you pull from master again itll show you the conflict

I have resolved conflicts. Can you please have look now.

**Review by Tyrepo1 — APPROVED** [review]
Looks good

**Pull request merged**
