### PR TITLE
Small Area Population Growth & Active Transportation

### PR DESCRIPTION
**Pull request by RhuthK**
Please have a look at my work and let me know if I need to change anything. Thanks :)

### CODE REVIEW

**Comment by TharushaCao** [comment]
@RhuthK 
Reminder :
- delete the: DELETE BEFORE PUBLISHING in the future pull request when use case is complete
- Update the "Learning Opportunities " Section currently blank
-  Add descriptions to the visualization and if possible.
- Add some more markdown headings or more description on your code when necessary 

Changes need to be made:

- Use the API method to get the datasets, currently I see ur just downloading it 
- Please don't upload the CSV files as it takes a lot of space(Delete them) instead use the API method as mentioned above


Other than the "Changes need to be made" everything looks fine  work on the reminders as you progress in the use case

**Review by AliColli — COMMENTED** [review]
Good descriptions in markdown but some code missing comments - update this in final.
The API import is commented out and CSV is used - you should be using API import in your use case. This is the most recent API with no limit: https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/usecases/ODSQL_API_v2_1_2024_tutorial_v2.ipynb

**Review by TharushaCao — APPROVED** [review]
Please delete any csv files before merging

**Review by AliColli — APPROVED** [review]
Looking good so far! don't forget to remove this from the beginning: {Write your introduction here. Keep it concise. We're not after "War and Peace" but enough background information to inform the reader on the rationale for solving this problem or background non-technical information that helps explain the approach. You may also wish to give information on the datasets, particularly how to source those not being imported from the client's open data portal.}

**Comment by AliColli** [comment]
Ready to merge, Rhuth :)

**Comment by leakydishes** [comment]
Hi @RhuthK this branch as conflicting files and you need to resolve conflicts. It is has diverged to far from main, I understand how frustrating this can be! I have closed this pull request. Please refetch and then select same reviewers with a comment to speed up the review process.

**Pull request closed without merging**
