### PR TITLE
Upload page UI

### PR DESCRIPTION
**Pull request by plhagyal**

### CODE REVIEW

**Comment by leakydishes** [comment]
Hi @plhagyal 
You need to add to reviewers to your code. Also this branched faced an error. You need to 'rebase' with main and then pull request. Reach out if you need any help. Review 'onboarding documentation' which goes through these steps.

**Review by leakydishes — CHANGES_REQUESTED** [review]
Hi @plhagyal
You need to add to reviewers to your code. Also this branched faced an error. You need to 'rebase' with main and then pull request. Reach out if you need any help. Review 'onboarding documentation' which goes through these steps.

**Comment by kaseyuu** [comment]
Hi, there is an unexpected token `div`. Expected jsx identifier.

**Comment by kaseyuu** [comment]
[Upload page Frontend development (max1)](https://trello.com/c/rztdORyT/543-upload-page-frontend-development-max1)

**Pull request closed without merging**
