### PR TITLE
DATA SCIENCE Green Wall, Accidents and Pedestrians, Bin Fill Levels 100% completed

### PR DESCRIPTION
**Pull request by AliColli**
Finalisation of use cases:

Green Walls,
Bin Fill Levels,
Pedestrian Accidents and Bus Stops

- updates to code and markup in all
- Add JSON files
- Add html files

### CODE REVIEW

**Comment by AliColli** [comment]
Sorry just realized I copied the green walls and didn't delete it from the needs "updating folder." So that old copy is deleted now to avoid confusion next trimester :)

**Comment by AliColli** [comment]
[New Use Case: Pedestrian Accidents and Bus-stops](https://trello.com/c/8RLzUYs8/521-new-use-case-pedestrian-accidents-and-bus-stops)

**Comment by AliColli** [comment]
[Rewrite - Green Wall Locations: Melbourne](https://trello.com/c/nmwYA5CV/511-rewrite-green-wall-locations-melbourne)

**Comment by AliColli** [comment]
[Pull requests documentation](https://trello.com/c/XxR5PwLS/539-pull-requests-documentation)

**Comment by AliColli** [comment]
Also I just checked and its the least recent files first in the filces changed tab... The newest are at the bottom where there are three use cases along with their html and JSON moved into the READY TO PUBLISH folders. Sorry so many files there its hard to check this one.

**Review by Samiha-Haque — APPROVED** [review]
Hi @AliColli, all the 3 usescases look good along with the 3 files for each. The documentation images a bit blurry but overall everything looks all good. Remember to delete your branch after merging.

**Pull request merged**
