### PR TITLE
WD_Frontend_Chaya#PR4

### PR DESCRIPTION
**Pull request by chaya221071557**
SignUp Page Multi-language functionality

### CODE REVIEW

**Review by Tyrepo1 — COMMENTED** [review]
are the changes in package-lock.json intentional? Have you added new packages?

**Comment by chaya221071557** [comment]
No, I did not add any new packages on my own.  The files shows some changes when I do npm install at the beginning.

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
Create a new branch from master. Copy your changes and dont run "npm i" so the package-lock file isnt changed

**Comment by chaya221071557** [comment]
okay.

**Comment by chaya221071557** [comment]
Made the suggested changes and created a new pull request which has been approved and merged. The name of the new pull request is WD_Frontend_Chaya#PR5.

**Pull request closed without merging**
