### PR TITLE
Air Quality Prediction - Completed ( Tharusha Cao ) 

### PR DESCRIPTION
**Pull request by TharushaCao**
This would be my final pull request in regard for my use case : Air Quality Prediction (Argyle Square)

Air Quality Dataset: https://data.melbourne.vic.gov.au/explore/dataset/argyle-square-air-quality/table/?sort=time
Activity Monitor Dataset:https:https://data.melbourne.vic.gov.au/explore/dataset/development-activity-monitor/table/?disjunctive.status&disjunctive.clue_small_area&disjunctive.clue_block

Trello card: https://trello.com/c/U3LTnPuR

### CODE REVIEW

**Comment by TharushaCao** [comment]
[New Use Case - Air Quality Prediction (Argyle Square)](https://trello.com/c/U3LTnPuR/445-new-use-case-air-quality-prediction-argyle-square)

**Review by RhuthK — CHANGES_REQUESTED** [review]
- Please add user story to the usecase description, here is an example of a user story  https://www.atlassian.com/agile/project-management/user-stories  . This will help in understand different people who will benefit from the findings in this usecase. 

- See if you can handle the FutureWarnings in your usecase. As this is a final merge it needs to be rectified. 

- Your use case is missing references of packages, online resources, libraries used in this unit. As this is the final merge it needs to be added at this point. 

- Please add a Conclusion section at the end which demonstrates the achievements for this usecase and how the findings from this use case will benefit business stakeholders, policy makers of city of melbourne, general audience (or any other relevant stakeholders that this use case was targeted towards.)

**Comment by TharushaCao** [comment]
> * Please add user story to the usecase description, here is an example of a user story  https://www.atlassian.com/agile/project-management/user-stories  . This will help in understand different people who will benefit from the findings in this usecase.
> * See if you can handle the FutureWarnings in your usecase. As this is a final merge it needs to be rectified.
> * Your use case is missing references of packages, online resources, libraries used in this unit. As this is the final merge it needs to be added at this point.
> * Please add a Conclusion section at the end which demonstrates the achievements for this usecase and how the findings from this use case will benefit business stakeholders, policy makers of city of melbourne, general audience (or any other relevant stakeholders that this use case was targeted towards.)

Made changes :)

**Review by twar9432 — APPROVED** [review]
The work looks really good with good conclusions, but there are some comments:
 - Consider readability. There's cells with long outputs that could be cleared as well as cells primarily useful to you as the DS, not the reader, like many df heads. If you think they're telling something important to the reader, you'd need to explain it more as it's not self-evident. 
 - Proof reading the markdowns are necessary since there's no spell check. There's quite a few spelling errors.

**Comment by TharushaCao** [comment]
> The work looks really good with good conclusions, but there are some comments:
> 
> * Consider readability. There's cells with long outputs that could be cleared as well as cells primarily useful to you as the DS, not the reader, like many df heads. If you think they're telling something important to the reader, you'd need to explain it more as it's not self-evident.
> * Proof reading the markdowns are necessary since there's no spell check. There's quite a few spelling errors.

:)

**Pull request merged**
