### PR TITLE
Completed tree canopy use case for review.

### PR DESCRIPTION
**Pull request by twar9432**
_Pull Request For Draft Use Case for Review_

The analysis focused on capturing whether development activities are linked to tree canopy changes from 2011-2021. This was done by:

- capturing and cleaning the data;
- creating GeoDataFrame for mapping;
- using the 'buffer' feature to find trees adjacent to development sites; and
- mapping and completing clustering analysis on the results.

**Note:** I was unable to get around the 10,000 row API limit for the tree datasets, despite extensive efforts. All cell outputs should show correct results, however if the need to run the cells again presents itself, please download the datasets from the links below.

MoP Tree Dataset 2021: https://data.melbourne.vic.gov.au/explore/dataset/tree-canopies-2021-urban-forest/export/
MoP Tree Dataset 2021:https://data.melbourne.vic.gov.au/explore/dataset/tree-canopies-2011-urban-forest/export/

Trello card: https://trello.com/c/o3hLJvzN/478-new-use-case-tree-canopy-changes

### CODE REVIEW

**Comment by twar9432** [comment]
[New Use Case - Tree Canopy Changes](https://trello.com/c/o3hLJvzN/478-new-use-case-tree-canopy-changes)

**Comment by TharushaCao** [comment]
[New Use Case - Air Quality Prediction (Argyle Square)](https://trello.com/c/U3LTnPuR/445-new-use-case-air-quality-prediction-argyle-square)

**Comment by TharushaCao** [comment]
Hey Thomas - as discussed in team chat . the following changes :

1. Update the getting of the datasets through the NEW API
2. If possible can the results of the cluster be in a table/df ( removes the need to zoom in the map to see the results)

**Review by AliColli — COMMENTED** [review]
For the API code, go to MOP, datascience, usecases, and use the code is ODSQL API https://github.com/Chameleon-company/MOP-Code/blob/master/datascience/usecases/ODSQL_API_v2_1_2024_tutorial_v2.ipynb

**Comment by twar9432** [comment]
The API call is finalised. After some experimentation I've decided to leave the table of tree loss/gain off the report. It is a 1000+ dataframe with a geopoint, development number, and tree loss number which is confusing to look at. I think the map displays the information best.

**Comment by TharushaCao** [comment]
> The API call is finalised. After some experimentation I've decided to leave the table of tree loss/gain off the report. It is a 1000+ dataframe with a geopoint, development number, and tree loss number which is confusing to look at. I think the map displays the information best.

all good :)

**Review by AliColli — APPROVED** [review]
All good :)

**Review by TharushaCao — APPROVED** [review]

**Pull request merged**
