### PR TITLE
DATA SCIENCE Pedestrians Bus Stops Use Case 100% completed

### PR DESCRIPTION
**Pull request by AliColli**
Pedestrians bus stops use case:
- Import data using API v2.1 GET request with /exports extension
- Import libraries, check for missing /null values in order to have a clean dataset
- Data visualisation by using matplotlib, dataframes, Geopandas
- Convert between Geodataframes and dataframes
- Use Geopandas to take subsamples of Geodataframes
- Allow user input
- Resample dataframes using date_time
- Mapping with folium incuding custom markers
- Oversampling, Undersampling and bootstrap approaches for imbalanced data classes
- Predictive modelling with Logistic Regression and Random Forest
- Understand results of confusion matrix, accuracy score and classification reports

### CODE REVIEW

**Comment by AliColli** [comment]
@twar9432 @yashdawaree Please review :)
The use case is the one that says "load diff" and it's having trouble with rendering, if that happens, open link with https://nbviewer.org/

**Comment by AliColli** [comment]
[New API and re-write Pedestrian Counts and Bus-stops](https://trello.com/c/8RLzUYs8/521-new-api-and-re-write-pedestrian-counts-and-bus-stops)

**Review by twar9432 — CHANGES_REQUESTED** [review]
Overall, the use case looks good. There's clear comments of the code and good analysis. 
**Note:** There's a plot shown as a 'map' with the axes as longitude and latitude, however without any background it's difficult to know its purpose. An update is needed to include this. Your other maps use folium effectively, I recommend that for this as well.

**Comment by AliColli** [comment]
@twar9432 Thanks for the feedback!
Geopandas map added into code. Please review again when you are able to :)

**Review by yashdawaree — APPROVED** [review]

**Comment by AliColli** [comment]
Also sorry @twar9432 I accidentally pushed through commits from another project as well (Green Walls). Feel free to review or ignore, its a work  in progress!

**Comment by AliColli** [comment]
@twar9432 map updated and ready for review :)

**Review by twar9432 — APPROVED** [review]

**Pull request merged**
