### PR TITLE
Data Science Team - Daljeet - Urban Development Analysis - sprint 3 pull requests - 100% done

### PR DESCRIPTION
**Pull request by PDALJEET**
Sprint 3 pull request 
Use Case : Urban Development Analysis
Worked on all the feedback from reviewers and was approved in week 8 and this is the final pull request for week 9 with all three format of the use case in json,html and ipynb format.

### CODE REVIEW

**Review by TharushaCao — CHANGES_REQUESTED** [review]
IMPORTANT - PLEASE use the API function instead of Downloading the dataset 


 If possible add a conclusion , other than not using the API get functions to get the dataset your use case if fine , please @ me when make changes

**Review by TharushaCao — APPROVED** [review]
Looks good

**Review by Sachithak95 — APPROVED** [review]

**Comment by leakydishes** [comment]
@TharushaCao and @Sachithak95 - this pull request has been closed. 
The member is required to place files into 'READY_TO_BE_PUBLISHED' not in playground.

@PDALJEET - You need to do the following ASAP
1. Move your files to a new directory in 'READY TO BE PUBLISHED'
2. Delete your old directory in PLAYGROUND. 
3. Re-request Pull request 
4. After you have been re-approved you can then merge pull request.

**Comment by twar9432** [comment]
[New Use Case - Prediction of Energy Use by Use Typology](https://trello.com/c/8FioCrJZ/558-new-use-case-prediction-of-energy-use-by-use-typology)

**Pull request closed without merging**
