### PR TITLE
DS - Banner Poles Booking Use Case 100% Complete - Sprint 3 

### PR DESCRIPTION
**Pull request by chihoang239**
- Update Time-series Analysis 
- Update seasonal analysis
- Update Recommendations

### CODE REVIEW

**Comment by jamie239** [comment]
Latest Update on 13/05:
- Add recommendation
- Add JSON file
- Add HTML file

**Comment by kitkatch** [comment]
Hi Jamie, great work.  The comments explanations and conclusions were all done well. 
Were the codes for the prophet model left out and not run deliberately? 
Screenshot 2024-05-14 at 3 37 32 PM

**Review by kitkatch — APPROVED** [review]
Hi Jamie, great work.  The comments explanations and conclusions were all done well. 
Were the codes for the prophet model left out and not run deliberately? 
Screenshot 2024-05-14 at 3 37 32 PM

**Review by Sachithak95 — APPROVED** [review]

**Comment by leakydishes** [comment]
Hi @jamie239 
You need to do the following ASAP

If you have the following files:
.html
.json
.ipynb

1. Move your files to a new directory in 'READY TO BE PUBLISHED'
2. Delete your old directory in PLAYGROUND. 
3. Re-request Pull request 
4. After you have been re-approved you can then merge pull request. 

otherwise if you only have following files:
.ipynb

1. Move your files to a new directory in 'UPDATED NEEDED'
2. Delete your old directory in PLAYGROUND. 
3. Re-request Pull request 
4. After you have been re-approved you can then merge pull request. 

Thank you.

@Sachithak95 and @kitkatch - please review as we need members to move files to correct location for last pull requests! Thank you!

**Comment by jamie239** [comment]
Thank you @kitkatch for the feedback, I have updated outputs from these two code cells and deleted the old directory in Playground, please re-check the pull request

**Comment by kitkatch** [comment]
Hi @jamie239 That's great, thank you.  Might just need to update the html file to reflect and show the output of the two updated cells.  Once that's done, your use case looks good to me.

**Comment by jamie239** [comment]
[New Use Case - Banner Poles Booking](https://trello.com/c/lEwcGcaM/524-new-use-case-banner-poles-booking)

**Pull request merged**
