### PR TITLE
WD_Frontend_Shevin_and_Upeksha #PR4

### PR DESCRIPTION
**Pull request by Shevin1**
Contributions:
Upeksha's Contributions:
1.Form Logic:

  Email and password input management.
  Validation of email and password.
  Toggling password visibility.
  Login button action and error handling.
2.Design of the Login Form:
Styling for the login box, input fields, and buttons.
Layout of the form and button styles.

Shevin's Contributions:
1.Container and Overall Layout:

  Structure the overall page layout using flexbox or another layout system to center the login box and header.
  Ensure consistent spacing, alignment, and margins across different components for a polished look.
2.Header Styling:

  Style the header to be fixed at the top, with proper padding, spacing, and shadow effects.
  Ensure the header scales properly on smaller screens (i.e., responsive design).
  Add media queries to adjust layout and positioning for mobile and tablet views.
3.Navigation Link Styling:

  Style navigation links to be visually appealing and easy to read, using proper font sizes, colors, and hover effects.
  Ensure proper padding between navigation items and that the links are spaced evenly across the header.

### CODE REVIEW

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
image
image
Screens dont look the same and theres a merge conflict

**Comment by Upekshadil** [comment]
the task they gave us is to make the login page not the sign up page and this is the one we updated
Screenshot 2024-09-14 221222

**Comment by Tyrepo1** [comment]
My point was to make the login page you guys are responsible for look like the sign up page so consistency is maintained in the website. The current login page you guys have developed looks very unpolished and basic.

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
image
Why does it say login. before every word

**Comment by Upekshadil** [comment]
well honestly we have no idea because when we run the code there is nothing like that. this is the output we got
Screenshot 2024-09-15 134100

**Comment by Tyrepo1** [comment]
It has something to do with the language functionality. Check if it's implemented correctly
Also you guys have merge conflicts with the current login page

**Comment by Shevin1** [comment]
We didn't complete the language functionality task, it was done by someone else.

**Comment by Shevin1** [comment]
the login. which appears before every word is not an error on our side its an error on language functionality, just need to double check that

**Pull request closed without merging**
