### PR TITLE
DATA SCIENCE Bird Habitat Analysis Use Case and Repointing Smart Bin Waste Collection AI Application - Both 100% Complete 

### PR DESCRIPTION
**Pull request by kitkatch**
Final Pull Request

Use Case includes:

File 1: 
Use case introduction
Table of Content
Accessing the two relevant datasets through the use of APIs
Pre-processing of the two data frames
Visualisations to understand the two datasets
Combination of two data frames
Maps included to show sightings and species of birds
Bird sighting prediction through random forest and gradient boosting
Mock data created
Random Forest and gradient Boosting used on mock dataframe
Conclusion

File 2: 
json 

File 3: 
Html

### CODE REVIEW

**Comment by kitkatch** [comment]
Also added repointing of use case Smart Bin Waste Collection AI Application

**Comment by kitkatch** [comment]
[New Use Case - Bird Habitat Analysis](https://trello.com/c/8Emr1mj9/312-new-use-case-bird-habitat-analysis)

**Comment by kitkatch** [comment]
[New API - Smart Bin Waste_Collection AI Application](https://trello.com/c/YrJJOZC8/518-new-api-smart-bin-wastecollection-ai-application)

**Comment by leakydishes** [comment]
Hi @kitkatch

You need to re fetch from main, vercel plug in for WEB has an error - 
Screenshot 2024-05-15 at 3 11 46 pm

Please do this ASAP and then request for your reviewers. 

Thank you!

**Review by leakydishes — CHANGES_REQUESTED** [review]
Hi @kitkatch

You need to re fetch from main, vercel plug in for WEB has an error -

Please do this ASAP and then request for your reviewers.

Thank you!

**Review by RhuthK — CHANGES_REQUESTED** [review]
Hello Katrine, 
Great work on the usecase. Please add reference section to this. Thanks.

**Comment by kitkatch** [comment]
Hi @RhuthK, thank you very much for the review, please find that I have now added references to my use case.  Thank you very much.

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi @kitkatch the usecases look great! However, you need to move your Smart Bin Waste Collection AI Application usecase folder to READY TO PUBLISH as well. And this usecase needs the .json file but you have uploaded a .js file instead.

**Review by Samiha-Haque — APPROVED** [review]
Great job! @kitkatch 
Remember to delete your branch after merging!

**Review by Samiha-Haque — APPROVED** [review]

**Review by Samiha-Haque — APPROVED** [review]

**Review by leakydishes — APPROVED** [review]
@kitkatch great job!

**Review by RhuthK — APPROVED** [review]
Great work, cheers!

**Pull request merged**
