### PR TITLE
WD_loginpage_Abanob MIkhael #PR2[FIXED]

### PR DESCRIPTION
**Pull request by ABANOBMIKHAEL**
Trello card : Sign up & Login page Frontend development (https://trello.com/c/EMR4E4vm )
Item 1 -> Login Page UI
Item 2 -> Fixed the responsiveness 
Item 3 -> Login page function

### CODE REVIEW

**Review by kaseyuu — CHANGES_REQUESTED** [review]
Hi Abanob, could you please adjust CSS to make the login page more consistent with the design? (more spacing between the form fields)

**Comment by Tyrepo1** [comment]
Hi Abanob! Furthermore, can you change the color palette and the text box size so it matches the signup page? Thanks

**Comment by Sakif-Hasan** [comment]
Closing the PR as the member has not updated the code according to the feedbacks given and has not solved the merge conflict.

**Comment by Sakif-Hasan** [comment]
Closing the PR as the member has not updated the code according to the

**Pull request closed without merging**
