### PR TITLE
(WIP) Customer Service Analysis

### PR DESCRIPTION
**Pull request by carissawong**
The code includes fetching the data, data cleansing, aggregation and some visualization.

### CODE REVIEW

**Review by HarleyNgo — COMMENTED** [review]
I wonder if you want to run again the notebook so that the visualizations appear, as for now it does not
I'll approve if you just want to keep it as it is now.

**Comment by carissawong** [comment]
Hi Harley, I already re-run the code and the visualizations should be appeared now.

**Review by AliColli — COMMENTED** [review]
Hi Carissa, plots are still not rendering in GitHub, maybe see if there is another option you can do? Usually, they just leave a blank space where they should render in if they won't load. Also consider using .head(3) when checking dataframes or a shape function? Just to reduce the length of the use case in outputs.

**Comment by HarleyNgo** [comment]
it still does not show visualizations but i still approve for this time
let's find a way to solve it next pull request

**Review by HarleyNgo — APPROVED** [review]

**Comment by carissawong** [comment]
Thank you Harley! I'll figure it out in the next pull request!

**Pull request merged**
