### PR TITLE
(DS) CS Analysis Use Case & Real-time Parking Hotspots API Update - 100%

### PR DESCRIPTION
**Pull request by carissawong**
I initially pushed the files to my own folder, but then I realised that I should push the files to ‘READY TO PUBLISH’. So, I created a pull request again.

Customer Service Analysis:
- Added a final overall conclusion
- Included the files in .html, .json, and the .ipynb file itself

Real-time parking hotspot updates:

1. API updates:
Updated the API for the three datasets. Users are no longer required to input their API key, and the entire dataset can now be fetched

2. Updated the JSON file to reflect changes in data handling

3. Enhanced Error Handling:
Improved code robustness to handle errors more effectively, particularly in situations where plots cannot be generated due to the absence of daily records.

4. Renamed Columns for Consistency:
Adjusted column names to align with the latest nomenclature used by the City of Melbourne. Specifically, 'parkingbay_id' and 'bayid' have been replaced with 'kerbsideid'

5. Further Editing and Arrangement:

- Arranged all package installations in one cell at the beginning of the scripts.
- Split the 'location' string in the 'on-street-parking-bay-sensors' dataset into latitude and longitude.
- Ensured 'status_timestamp' is timezone-aware and set to UTC before converting it to Melbourne local time.
- Removed scripts for splitting latitude and longitude from the 'on-street-parking-bays' dataset because the updated dataset already includes these two separate columns.
- Removed scripts for rounding latitude and longitude to six decimal places because the initial dataset already does this.
- Filtered to ensure only numeric 'kerbsideid' values are used for merging.
- Changed merging strategy to use 'kerbsideid' as the key identifier instead of latitude and longitude.
- Checked for and removed any duplicated rows.
- Renamed 'bayid' in the third dataset 'on-street-car-park-bay-restrictions' as 'kerbsideid' to maintain consistency with the other two datasets.

### CODE REVIEW

**Review by AliColli — APPROVED** [review]
looks ok to me :)

**Comment by carissawong** [comment]
thanks @AliColli :D

**Comment by carissawong** [comment]
[New API - Real-time parking hotspots](https://trello.com/c/HsnNonbP/519-new-api-real-time-parking-hotspots)

**Comment by carissawong** [comment]
[New Use Case - Customer Service Analysis](https://trello.com/c/AbQphoyq/448-new-use-case-customer-service-analysis)

**Pull request merged**
