### PR TITLE
WD|Build|Multilanguage Function

### PR DESCRIPTION
**Pull request by kaseyuu**
Set up multilanguage function

### CODE REVIEW

**Comment by Sakif-Hasan** [comment]
Closing the PR as team member is working on some updates.

**Comment by kaseyuu** [comment]
Can you please merge it. My future updates need to be based on this one.

**Comment by kaseyuu** [comment]
Can you please merge it. My future updates need to be based on this one.

**Review by Sakif-Hasan — APPROVED** [review]

**Comment by kaseyuu** [comment]
[Multilanguage function (max 1)](https://trello.com/c/xjTX26Ta/551-multilanguage-function-max-1)

**Pull request merged**
