### PR TITLE
Enhancing Pedestrian Safety in Melbourne's Urban Areas -DS 

### PR DESCRIPTION
**Pull request by dTitanium**
Final pull request for this trimester T1 24.
Corrected issues with my previous pull request #533
 - Issues with my forked version (corrected)
Sprint 03 end

### CODE REVIEW

**Review by TharushaCao — COMMENTED** [review]
- Please rename the template with your use case
- Remove any data frame files which are not used before publishing 
- remove txt file

**Comment by Sachithak95** [comment]
There are few empty code cells in the final part of your code, remove them before merging.

**Review by Sachithak95 — APPROVED** [review]
Include the html file before merging

**Comment by dTitanium** [comment]
[New Use Case - Enhancing Pedestrian Safety in Melbourne's Urban Areas](https://trello.com/c/qDby8CZE/434-new-use-case-enhancing-pedestrian-safety-in-melbournes-urban-areas)

**Comment by dTitanium** [comment]
[New Use Case - Enhancing Pedestrian Safety in Melbourne's Urban Areas](https://trello.com/c/qDby8CZE/434-new-use-case-enhancing-pedestrian-safety-in-melbournes-urban-areas)

**Pull request merged**
