### PR TITLE
Data Science - Exploring Greening Laneways and Urban Forest Strategy - completed and Analyzing Traffic Congestion, Speeding, and Accident Correlation -80% Complete

### PR DESCRIPTION
**Pull request by Sabihulhassan98**
Week 10 final pull request from Sprint 3
Use Case Exploring Greening Laneways and Urban Forest Strategy - 100% Completed
Includes:

1.	Imported data using API v2.1 
2.	Data Manipulation and Cleaning
3.	Cluster Analysis and Geospatial Visualization
4.	Comparing Greening Scenarios
5.	Modeling and Predictive Analysis
6.	Comparing Model Performance
7.	Time-Series Analysis
8.	Spatial Correlation and Indicator Analysis
9.	Conclusion and Recommendations

Use Case: Traffic Congestion, Speeding, and Accident Correlation Analysis 80% completed
Includes:
1.	Data Import and Cleaning
2.	Exploratory Data Analysis (EDA)
3.	Temporal Analysis of Accidents and Speeding
4.	Road Geometry and Accident Severity Analysis
5.	Correlation Analysis
6.	Cluster Analysis of High-Risk Roads
7.	Accident Severity Prediction (Initial Model Development)

### CODE REVIEW

**Comment by Sabihulhassan98** [comment]
Hi @SaiPriyamvada21 and @dTitanium, can you please review my pull request so that I can merge it with the master.

**Comment by Sabihulhassan98** [comment]
Hi @remmzytom, Please review this pull request and let me know if its ready to merge.

**Comment by remmzytom** [comment]
HI @Sabihulhassan98  Analyzing traffic use case it would be nice if you can let all the files have the same name convention

and for the Exploring Grenning Laneways Traffic you it would be nice if you can add some references to your conclusion.

**Comment by Sabihulhassan98** [comment]
I have fixed the name convention  Traffic Congestion, Speeding and Accident Correlation Analysis and also added References for Exploring Greening Laneways use case

**Review by remmzytom — APPROVED** [review]

**Pull request merged**
