### PR TITLE
Data Science Team - Urban_Growth_and_Transit_Planning_for_Melbourne (100%)

### PR DESCRIPTION
**Pull request by Manasa-n1**
Final pull request review for sprint 3

Use case includes:

•	Loaded all three datasets through API
•	Cleaning data to ensure it is standardised and consistent
•	Separating and merging dataframes
•	Multiple visualizations comparing different variables using histogram,boxplot,  barplot,heatmap
•	Analysing these visualizations, seeing how the variables impact the results
•	visualizing metro stations, bus stops and population dataset on a map using Folium which is well-structured and the maps 
        is displaying with all metro stations, bus stops, population.
•	Implemented two machine learning model linear regression and random forest model to predict the population trend.
•	Visualizing these results with scatter plot
•	Updated with the model conclusion and reference

### CODE REVIEW

**Review by Jnaneshwari-beerappa — APPROVED** [review]
Good work,  ready to merge

**Review by Sachithak95 — CHANGES_REQUESTED** [review]
Hi @Manasa-n1,

You've done great work with your use case and the guide document. However, unfortunately, I cannot approve this due to a few errors in both the use case and the guide document.

For your use case, please ensure that the title is in the proper font size. In the guide document, please make sure to add a conclusion and mention that it is Version 1 with the respective year.

For example, you could write like "Manasa 2024.V1."

Overall, you've done great work, just a few small adjustments needed!

Thank you!

**Comment by Manasa-n1** [comment]
> Hi @Manasa-n1,
> 
> You've done great work with your use case and the guide document. However, unfortunately, I cannot approve this due to a few errors in both the use case and the guide document.
> 
> For your use case, please ensure that the title is in the proper font size. In the guide document, please make sure to add a conclusion and mention that it is Version 1 with the respective year.
> 
> For example, you could write like "Manasa 2024.V1."
> 
> Overall, you've done great work, just a few small adjustments needed!
> 
> Thank you!

Hi @Sachithak95 ,
I have made requested changes, Kindly review and let me if any changes required.
Regards,
Manasa

**Review by Jnaneshwari-beerappa — APPROVED** [review]
Looks good, please go ahead with merging

**Review by Sachithak95 — APPROVED** [review]
All the changes are done! :) You can now merge with master. Please make sure to delete your branch after merging. Great work! :)

**Pull request merged**
