### PR TITLE
Data Science - New Use Case -  Melbourne House Price Market Analysis

### PR DESCRIPTION
**Pull request by s220313209**
1. Introduction:
The aim of this proposal is to leverage available datasets to create a comprehensive analysis of the Melbourne housing market. By utilizing various datasets provided by the City of Melbourne and external sources such as Kaggle, we aim to develop insights into housing price trends, identify factors influencing house prices, and provide valuable information for buyers, sellers, real estate agents, investors, and policymakers.

2. Objectives:
Analyze the Melbourne House Prices dataset to understand historical and current housing price trends.
Utilize data on property sales transactions to assess market activity and price fluctuations.
Combine insights from various datasets to forecast future housing prices and identify high-demand areas.

### CODE REVIEW

**Comment by kitkatch** [comment]
Hi Bao, 

I can't see your ipynb with this pull, would you be able to re-pull with the right ipynb file please? 
Thanks.

**Review by s220313209 — COMMENTED** [review]
Hi Katrine,
I have added my code file and assigned you and Samiha as reviewers. Please take a look.
Thanks.

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi Bao,

1. Dataset-2(House prices uses read_csv instead of API2.1v, please use API2.1v for loading datasets.
2. Try to import all libraries at the very start of the whole code instead of in the middle like "from geopy.geocoders import Nominatim" in line 68
3. There is an error block in line 70, please fix that.
4. The final map at the end of the notebook is not visible.

**Review by kitkatch — COMMENTED** [review]
Hi Bao, 

Overall looks good as I am sure you are still working on this and changes are still being made to make sure everything works the way you want it to.  However, is one of your df an external data, if so, you may need to load your csv file into your folder in order for users to be able to work with this.  

Additionally, not very important for sprint 1, but for your final submission, maybe consider adding more comments explaining what you are doing so that your reader would know why you have done what you have done. Remember that this is a tutorial for your reader.

Please also save your external df to this folder. :)

**Comment by s220313209** [comment]
> Hi Bao,
> 
> 1. Dataset-2(House prices uses read_csv instead of API2.1v, please use API2.1v for loading datasets.
> 2. Try to import all libraries at the very start of the whole code instead of in the middle like "from geopy.geocoders import Nominatim" in line 68
> 3. There is an error block in line 70, please fix that.
> 4. The final map at the end of the notebook is not visible.

Hi Samiha, 

Thank you for your comment. I have modified the code, note that the dataset 2 I used external data.
This is just the preprocessing step before applying more technique.
Please let me know if I need to change anything. 

Regards,

**Comment by s220313209** [comment]
> Hi Bao,
> 
> Overall looks good as I am sure you are still working on this and changes are still being made to make sure everything works the way you want it to. However, is one of your df an external data, if so, you may need to load your csv file into your folder in order for users to be able to work with this.
> 
> Additionally, not very important for sprint 1, but for your final submission, maybe consider adding more comments explaining what you are doing so that your reader would know why you have done what you have done. Remember that this is a tutorial for your reader.
> 
> Please also save your external df to this folder. :)

Hi Kat,

Thank you for your comment, I have modified the code and add the csv file to the folder.

**Review by Samiha-Haque — APPROVED** [review]
@s220313209  Looks great!
Approved.

**Pull request merged**
