### PR TITLE
New Use Case - Enhancing Pedestrian Safety in Melbourne's Urban Areas

### PR DESCRIPTION
**Pull request by dTitanium**

### CODE REVIEW

**Comment by TharushaCao** [comment]
@HarleyNgo Can you look at this? huge file changes?

**Comment by molliefernandez** [comment]
Please Provide a description for your work

**Comment by molliefernandez** [comment]
- You can probably remove the "API method 1" unless its part of your tutorial...
- In your next git push please include a use case description etc, use the template to see what this looks like. Can be found here: datascience/usecases/usecase_TEMPLATE.ipynb
- Love the heading which break up each of the sections and let the reader know what you are going to do next. Would love to see more of a description explaining what you are doing. Remember this is meant to be a tutorial.
- Maybe edit the last line of code so that it doesn't print all of those locations, it's making your use case really large! 
- But it looks great so far, definetly going to be a great use case when you are finished with it!

**Comment by HarleyNgo** [comment]
Hi Dinuk
Your branch still seems totally different from the master branch, in terms of how the the folders organized.
Please clone the master branch, create your branch and upload your file again then you're ready to merge.

**Comment by leakydishes** [comment]
HI @dTitanium I have closed this pull request as your branch has diverged to far from main. You need to fetch as per reviewers comments made 2 weeks ago. You can then submit a new pull request.

**Pull request closed without merging**
