### PR TITLE
DATA SCIENCE Team - Air Quality based on Environmental factors - 60%

### PR DESCRIPTION
**Pull request by alireza-montazeri**
**Sprint 1 (Week 5) Pull Request:**
This pull request introduces changes to the _DataExploring.ipynb_ file. The main goal of these changes is to explore the dataset and perform initial data analysis.

**Changes Made:**

- **Data Loading:** Added code to load the dataset from Melbourne Open Data API v2.1.
- **Data Cleaning:** Implemented data cleaning steps, including:
-- Handling missing values
-- Removing duplicates
-- Converting data types
- **Data Visualization:** Created visualizations to understand the distribution and relationships within the data, including:
-- Histograms
-- Scatter plots
-- Correlation matrices
- **Initial Analysis:** Performed initial analysis to identify key trends and insights
- **Documentation:** Added markdown cells to document the steps and findings throughout the notebook.

Testing

- Verified that the dataset loads correctly.
- Ensured that all visualizations render without errors.
- Checked that the analysis results are consistent with expectations.

### CODE REVIEW

**Review by HarshDW09 — COMMENTED** [review]
From my side , it looks good . Just wait for the approval from a Senior leader.

**Review by Samiha-Haque — CHANGES_REQUESTED** [review]
Hi Alireza!

1. Please rename your file with the name of your usecase
2. If possible include x and y axis labels in code line 6 and 19

**Comment by alireza-montazeri** [comment]
Hi Samiha, Harsh

Thank you for your comments.

I updated the notebook name and added labels to the plots that you mentioned.

**Review by Samiha-Haque — APPROVED** [review]
Looks good @alireza-montazeri.
A small tip: Keep your title of the ipynb file and the name of your file consistent. Your title is still "Exploring Greening Laneways and Urban Forest Strategy" which is not the same as the file. 
Other than that, all good! Approved.

**Pull request merged**
