### PR TITLE
Usecase: Relationship between cost of housing and landmarks and amenities of a suburb

### PR DESCRIPTION
**Pull request by vaibhavideo**
In this usecase we intend to understand what impact does the amenities of a suburb such as hospitals, places of worship, shopping centres, tourist attractions have on the housing market of the suburb.

### CODE REVIEW

**Comment by molliefernandez** [comment]
Please add 2 reviewers to approve your work

**Review by HarleyNgo — COMMENTED** [review]
i saw 2 files with quite similar content. can you add version for it, or delete the unnecessary one?
also if this is a collaborate usecase, I suggest having a mutual folder for both of you, so that the marking people can track and not find it vague.

**Comment by molliefernandez** [comment]
- Please redo the beginning of your use case so that you are calling data in from the CoM Open Data website rather that from the CSV file, this use case will not be included in the 'ready to publish' until this has been rectified. You can find the code for this here: datascience/usecases/ODSQL_API_v2_1_2024_tutorial_v2.ipynb

- Please add more written aspects to explain what you are doing and how you are manipulating the data at each step. Remember this is meant to be a tutorial for someone to follow and understand why you are doing each step.

**Comment by leakydishes** [comment]
No Action has been taken on this pull request for 2 weeks. I am now closing this request as your branch as diveraged to far from main. Please fetch and fix changes requested by reviewers before making pull request again. Thank you.

**Pull request closed without merging**
