### PR TITLE
WD_FRONTEND_THAMASHA-#PR2 

### PR DESCRIPTION
**Pull request by thamashag**
Styled the sign-up page for web to improve user experience. Adjusted CSS to ensure proper alignment and spacing.

### CODE REVIEW

**Comment by Tyrepo1** [comment]
Hey Thamasha! UI looks good. However, Can you implement the password strength function as well as make the login button route to /login page

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
Hey Thamasha! UI looks good. However, Can you implement the password strength function as well as make the login button route to /login page

**Comment by leakydishes** [comment]
Hi @thamashag can you review the comments made and make these fixes. Otherwise your branch will deverge to far from main and you will need to re fetch as it will cause deployment issues. If this pull request is left for more then 2 weeks - reviewers please close and request a fetch and new pull request.

**Comment by thamashag** [comment]
Hey @leakydishes  and @Tyrepo1 , I've addressed the comments and implemented the requested changes. The password strength function has been added, and the login button now correctly routes to the /login page. I've ensured that these updates align with the main branch to prevent any divergence and potential deployment issues. Let me know if there's anything else you'd like to see or if further adjustments are needed. Thanks for the feedback!

**Review by Tyrepo1 — APPROVED** [review]
Looks good!

**Pull request merged**
