### PR TITLE
Molliefernandez green roofs update

### PR DESCRIPTION
**Pull request by molliefernandez**
Moved from rework complete to ready to publish T1 2024 along with its dependencies. 
Removed old versions of the file.

### CODE REVIEW

**Comment by molliefernandez** [comment]
[New API - Green Roof Locations: Melbourne](https://trello.com/c/i5hQDwWl/510-new-api-green-roof-locations-melbourne)

**Comment by molliefernandez** [comment]
[Dependency Updates](https://trello.com/c/evMmzFTW/532-dependency-updates)

**Review by leakydishes — APPROVED** [review]
Looks fine old cases are not needed.

**Comment by leakydishes** [comment]
Approved you can merge @molliefernandez

**Pull request merged**
