### PR TITLE
MOP DS - Melbourne's Biodiversity usecase 100%

### PR DESCRIPTION
**Pull request by francisrusli**
finalised a few points in the usecase.

### CODE REVIEW

**Comment by francisrusli** [comment]
[New Use Case - Biodiversity in Melbourne's parks](https://trello.com/c/Ce7izqJQ/348-new-use-case-biodiversity-in-melbournes-parks)

**Comment by francisrusli** [comment]
[New Use Case - Biodiversity in Melbourne's parks](https://trello.com/c/Ce7izqJQ/348-new-use-case-biodiversity-in-melbournes-parks)

**Review by HarleyNgo — CHANGES_REQUESTED** [review]
please upload your files into READY TO PUBLISH/T1 2024 fi the usecase is done, else UPDATED NEEDED.
current files are still in your personal folders

**Review by leakydishes — CHANGES_REQUESTED** [review]
Hi @francisrusli 

Fixes needed:
1. Move your files to a new directory in 'READY TO BE PUBLISHED'
2. Delete your old directory in PLAYGROUND. 
3. Re-request Pull request 
4. After you have been re-approved you can then merge pull request.

**Comment by francisrusli** [comment]
Hi Te & Harley, 

I have moved my current files from playground to READY TO BE PUBLISHED T1 2024 and deleted my old directory in playground.

Thanks!
Francis Rusli

@leakydishes @HarleyNgo

**Pull request closed without merging**
