### PR TITLE
DS Support Services Usecase - Complete and ready to publish

### PR DESCRIPTION
**Pull request by VaishaliThakoor**
Added the html and json files and created folder in ready to publish

### CODE REVIEW

**Review by leakydishes — CHANGES_REQUESTED** [review]
Screenshot 2024-05-20 at 5 57 32 pm

Hey, you need to delete your directory in Playground. Can you do this and send me another request?

**Comment by VaishaliThakoor** [comment]
Thanks Te! I will make the changes and create another request!

**Review by leakydishes — APPROVED** [review]
Looks good

**Comment by leakydishes** [comment]
@VaishaliThakoor

**Comment by VaishaliThakoor** [comment]
Thank you!! :)

**Pull request merged**
