### PR TITLE
Tharusha cao - Updated Pull Request

### PR DESCRIPTION
**Pull request by TharushaCao**
- API update
- small use case change

### CODE REVIEW

**Comment by TharushaCao** [comment]
The graphs don't show when uploaded to GitHub, hence it's showing the -400000 deletions for that use case. works on my end tho :).

**Review by twar9432 — APPROVED** [review]
@TharushaCao Looks really good. Only comment would be that some of the early cell outputs are pretty massive. Consider clearing some for readability.

**Review by RhuthK — APPROVED** [review]
Good work. Approved :)

**Comment by TharushaCao** [comment]
[New Use Case - Air Quality Prediction (Argyle Square)](https://trello.com/c/U3LTnPuR/445-new-use-case-air-quality-prediction-argyle-square)

**Pull request merged**
