### PR TITLE
Data Science Team - Nearby Restaurant Hotspots Final - 100% Complete

### PR DESCRIPTION
**Pull request by sahanchamod**
Week 10 - Pull request for review -  Sprint 3

- Use case introduction
- Read data using API
- Explore data sets
- Data Preprocessing
- Impute missing data
- Descriptive analysis
- Classify restaurant hotspot using K Means clustering
- Identify restaurant hotspots

### CODE REVIEW

**Review by kitkatch — CHANGES_REQUESTED** [review]
HI Sahan, 

Great job on the use cases, however, please remove the config.py file, as we don't want to make any API key public.  Currently no API keys are required to pull data, therefore you can remove/comment out "api_key': API_KEY".  Please fix and I can approve after. :)

**Comment by sahanchamod** [comment]
Thank you for the feedback Katrine, I have fixed it now

**Review by kitkatch — APPROVED** [review]
All good, thanks. :)

**Comment by sahanchamod** [comment]
Thank you Kathrine, Dinuk and Tharaka for your feedback

**Pull request merged**
