### PR TITLE
Web_Dev_Frontend_Abhishek_Chiluks_PR3

### PR DESCRIPTION
**Pull request by abhishek-chiluka99**
Completed Upload Case Study page with working condition

image

image

### CODE REVIEW

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
For the inputs we only need to get The use case name (string), description(string) and tags(array of strings)
image
In the upload icon it says"Upload logo"?
image
Also make sure that the upload case studies text is in a single line


Note that Minh on the frontend team is redesigning the About Us page. So you should message Minh and collaborate with him so there will be no merge conflicts.

**Comment by abhishek-chiluka99** [comment]
Yes, Hoang ill do that changes, 

About us page I have not done any changes, might be entered space. But if Minh working on it i have no issues on it for any conflict he can do the changes.

**Comment by Tyrepo1** [comment]
It says you modified 170 lines of code in the about us page

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
image
Can you have the words be on the same line and same color

**Comment by abhishek-chiluka99** [comment]
Yes, Hoang completed those changes, Thank you

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
Were the changes to the about us file intended? If not, can you remove the changes you've made to the about us file

**Review by Tyrepo1 — CHANGES_REQUESTED** [review]
can you put the trimester selector in the Uploader's Deatail section
image
Also change Uploader's Details to Upload Details

**Review by Tyrepo1 — APPROVED** [review]
Looks good

**Pull request merged**
